# Generated by Django 6.0.6 on 2026-06-21 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_historicalproduct_historicalstock'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstock',
            name='purchase_order_item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='orders.purchaseorderitem'),
        ),
        migrations.AddField(
            model_name='stock',
            name='purchase_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_batches', to='orders.purchaseorderitem'),
        ),
    ]
