from rest_framework import serializers
from apps.inventory.models import Product, Stock

PRODUCT_NOT_FOUND = 'Product not found.'

class ProductSerializer(serializers.ModelSerializer):
    # This field will be populated by a database annotation in the ViewSet
    total_stock = serializers.DecimalField(max_digits=12, decimal_places=3, read_only=True, default=0)

    class Meta:
        model = Product
        fields = [
            'id', 'name', 'description', 'sku', 'unit_of_measure', 
            'total_stock', 'created_at', 'updated_at'
        ]
        read_only_fields = ['id', 'total_stock', 'created_at', 'updated_at']

    def validate_sku(self, value):
        """
        Ensure SKU is unique *per user*, allowing different users to use the same SKU.
        """
        request = self.context.get('request')
        if request and request.user:
            qs = Product.objects.filter(user=request.user, sku=value)
            # If updating an existing product, exclude it from the duplicate check
            if self.instance:
                qs = qs.exclude(pk=self.instance.pk)
            if qs.exists():
                raise serializers.ValidationError("A product with this SKU already exists in your inventory.")
        return value

class ProductFinancialSerializer(serializers.ModelSerializer):
    revenue = serializers.DecimalField(max_digits=12, decimal_places=2, read_only=True)
    cogs = serializers.DecimalField(max_digits=12, decimal_places=2, read_only=True)
    profit = serializers.DecimalField(max_digits=12, decimal_places=2, read_only=True)
    margin = serializers.DecimalField(max_digits=5, decimal_places=2, read_only=True)

    class Meta:
        model = Product
        fields = ['id', 'name', 'sku', 'revenue', 'cogs', 'profit', 'margin']

class StockSerializer(serializers.ModelSerializer):
    # Helpful read-only fields for the frontend so it doesn't have to make extra API calls
    product_name = serializers.CharField(source='product.name', read_only=True)
    product_sku = serializers.CharField(source='product.sku', read_only=True)

    class Meta:
        model = Stock
        fields = [
            'id', 'product', 'product_name', 'product_sku', 'lot_code', 
            'best_before', 'initial_quantity', 'current_quantity', 
            'unit_cost', 'created_at', 'updated_at'
        ]
        read_only_fields = [
            'id', 'product_name', 'product_sku',
            'created_at', 'updated_at'
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance is None:
            self.fields['current_quantity'].read_only = True

    def validate_initial_quantity(self, value):
        if value < 0:
            raise serializers.ValidationError("Initial quantity cannot be negative.")
        return value

    def validate_current_quantity(self, value):
        if value < 0:
            raise serializers.ValidationError("Current quantity cannot be negative.")
        return value

    def validate_product(self, value):
        """
        Crucial security check: Ensure the user owns the product they are adding stock to.
        """
        request = self.context.get('request')
        if request and request.user:
            if value.user_id != request.user.id:
                raise serializers.ValidationError(PRODUCT_NOT_FOUND)
        return value

    def validate(self, data):
        """
        Enforce business rules for stock editing.
        """
        if self.instance: # Update operation
            # 1. Block edits if generated by PO
            if self.instance.purchase_order_item_id:
                if 'initial_quantity' in data and data['initial_quantity'] != self.instance.initial_quantity:
                    raise serializers.ValidationError({
                        "Initial Qty": "This stock batch was generated by a Purchase Order and its quantity cannot be manually edited."
                    })
                if 'unit_cost' in data and data['unit_cost'] != self.instance.unit_cost:
                    raise serializers.ValidationError({
                        "Unit Cost": "This stock batch was generated by a Purchase Order and its cost cannot be manually edited."
                    })

            is_consumed = self.instance.current_quantity < self.instance.initial_quantity
            
            # 2. Block initial_quantity edits if consumed
            new_initial_qty = data.get('initial_quantity', self.instance.initial_quantity)
            if is_consumed and new_initial_qty != self.instance.initial_quantity:
                raise serializers.ValidationError({
                    "Initial Qty": "Cannot edit initial quantity because this batch has been partially or fully consumed."
                })
            
            # 3. current_quantity is normally read-only (Sales Orders deduct stock).
            #    Exception: unconsumed manual batches may be corrected (e.g. 100 entered instead of 1000).
            new_current_qty = data.get('current_quantity', self.instance.current_quantity)
            if new_current_qty != self.instance.current_quantity:
                if self.instance.purchase_order_item_id:
                    raise serializers.ValidationError({
                        "Current Qty": "This stock batch was generated by a Purchase Order and its quantity cannot be manually edited."
                    })
                if is_consumed:
                    raise serializers.ValidationError({
                        "Current Qty": "Current quantity is read-only and is automatically deducted by Sales Orders. Do not edit this manually."
                    })

        return data
